# Generated by Django 4.0.10 on 2023-09-06 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_author_user_alter_book_user_alter_genre_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_pages',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
